### ISSUE TITLE
Add monthly event repeat type based on weekday

### ISSUE THREAD

**Issue by pyrox18** [pyrox18/SchedulerBot#1]
This repeat type should cause an event to reschedule itself to the same day of the nth week in the following month.

e.g. `+event Test Oct 1 2018 9am --repeat mw` creates an event that falls on the first Monday of October 2018. The repeat trigger should reschedule the event to the first Monday of November 2018, which is 5 November 2018.

- [x] Create new repeat type in the `RepeatType` enum
- [x] Add repeat logic in `RepeatJob`
- [x] Add `mw` as argument for the `--repeat` flag
- [x] Update help commands for `+event` and `+event update`

**Comment by jespirit** [comment]
I'm a student and I'm going to be sign up for hacktoberfest (course requirement) and I want to learn more about C#. This was one of the first links that I found when I searched for issues using the C# language. I want to take on this issue if you don't mind.

**Comment by pyrox18** [comment]
Sure thing! Do make sure you read the [contributing guidelines](https://github.com/pyrox18/SchedulerBot/blob/master/CONTRIBUTING.md) first. Other than that, you can just follow the checklist I've provided to implement the feature.

Some pointers:
- The `RepeatType` enum is located [here](https://github.com/pyrox18/SchedulerBot/blob/c3f44f2fa5d73a7b99aba6f35e7813181dcaf5cb/SchedulerBot.Data/Models/Event.cs#L59). You can call the new enum entry `MonthlyWeekday`.
- The repeat logic for the new repeat type should be added [here](https://github.com/pyrox18/SchedulerBot/blob/c3f44f2fa5d73a7b99aba6f35e7813181dcaf5cb/SchedulerBot.Data/Services/EventService.cs#L279).
- The `--repeat` flag argument should be added somewhere [here](https://github.com/pyrox18/SchedulerBot/blob/c3f44f2fa5d73a7b99aba6f35e7813181dcaf5cb/SchedulerBot.Client/Parsers/EventParser.cs#L96).
- [This](https://github.com/pyrox18/SchedulerBot/blob/c3f44f2fa5d73a7b99aba6f35e7813181dcaf5cb/SchedulerBot.Client/Commands/HelpCommands.cs#L181) and [this](https://github.com/pyrox18/SchedulerBot/blob/c3f44f2fa5d73a7b99aba6f35e7813181dcaf5cb/SchedulerBot.Client/Commands/HelpCommands.cs#L255) should be updated to include the new `mw` option for repeats.

Feel free to ask if you get stuck anywhere.

**Comment by jespirit** [comment]
I was having trouble in step 6 of the "Installation and Usage" guide. I was getting the following error.

```
set "ASPNETCORE_ENVIRONMENT=Development" && dotnet ef database update -s ..\SchedulerBot.Client\SchedulerBot.Client.csproj
...
No password has been provided but the backend requires one (in MD5)
```

I had to change `ConnectionStrings.SchedulerBotContext` in `appsettings.Development.json` to include a user and password. So, (1) are you supposed to include a user and password or (2) is there a way to connect to the database without login credentials? I think this should be documented in the README file.

**Comment by pyrox18** [comment]
I didn't document that problem before this as it seems to be platform-dependent (I ran into it on Windows, but not on macOS), but I guess documenting it wouldn't hurt. Technically if you don't set a password on your PostgreSQL user, you're supposed to be able to access it without a password, but for some reason that doesn't work on Windows.
